@hostname=http://localhost:5000

###
# @name createUser
POST {{hostname}}/users/
content-type: application/json

{
	"first_name": "John",
	"last_name": "Doe",
	"email": "johndoe@example.com"
}

###
GET {{hostname}}/users/
content-type: application/json

###
GET {{hostname}}/users/{{createUser.response.body.$.user.id}}
content-type: application/json

###
DELETE {{hostname}}/users/{{createUser.response.body.$.user.id}}
content-type: application/json


