# https://www.youtube.com/watch?v=RcxvrhQKv8I

@hostname=https://httpbin.org

###
GET {{hostname}}/get?isGood=true&isBad=false

###
DELETE {{hostname}}/delete

###
POST {{hostname}}/post

{
    "name": "john deer",
    "permissions": [2000,3000,4000]
}

###
PUT {{hostname}}/put
Content-Type: application/x-www-form-urlencoded

name=john+deer&permissions=2000&permissions=3000&permissions=4000
